Replace cable_gw_hydro.F90 with its new version
CABLE-LSM/CABLE pull request #231
Opened 2024-04-07 11:31 UTC by rkutteh

# CABLE ground water hydrology work of Mengyuan Mu

This pull request is part of integrating the ground water hydrology work of Mengyuan Mu into CABLE, which will take place in a sequence of pull requests. The actual integration project itself was completed back in September 2023. The current work involves just a gradual merge into the main branch. 

## Description

1. cable_gw_hydro.F90 is replaced by its new version (drop-in replacement)
2. Dependencies are introduced in **src/offline/cable_parameters.F90**, **src/offline/cable_define_types.F90**, **src/science/soilsnow/cbl_thermal.F90**, and **src/util/cable_common.F90** in order for the code to compile successfully (confirmed)
3. *PLEASE* do not delete any of my in-code comments (tagged rk4417) for now. Once the integration of the ground water hydrology work is complete and its functionality is confirmed to reproduce the results obtained already outside of the repo, I will clean-up all of my comments in a single pull request. Deleting any of my comments now will just make it much more difficult for me to track down and fix any issues that might arise during this process.

2024-04-09 02:51 UTC, ccarouge commented
@rkutteh I have seen this but I think it is going to take some time. I believe I have to test it against the main version because there are things in there that can change the results without the groundwater on.

2024-04-09 03:06 UTC, rkutteh commented
Hi Claire,

no worries, take your time and let me know if you want more info about some of the changes I have made.
We can discuss more on Thursday.

Thanks.
Ramzi
________________________________
From: Claire Carouge ***@***.***>
Sent: Tuesday, 9 April 2024 12:51 PM
To: CABLE-LSM/CABLE ***@***.***>
Cc: Ramzi Kutteh ***@***.***>; Mention ***@***.***>
Subject: Re: [CABLE-LSM/CABLE] Replace cable_gw_hydro.F90 with its new version (PR #231)


@rkutteh<https://github.com/rkutteh> I have seen this but I think it is going to take some time. I believe I have to test it against the main version because there are things in there that can change the results without the groundwater on.

—
Reply to this email directly, view it on GitHub<https://github.com/CABLE-LSM/CABLE/pull/231#issuecomment-2044060711>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AXR2B4GODFGOTRW3JOCCRETY4NJUTAVCNFSM6AAAAABF3H5DZSVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDANBUGA3DANZRGE>.
You are receiving this because you were mentioned.

2024-06-18 00:04 UTC, ccarouge requested changes
I have finally finished reviewing this. I have a few minor comments, mainly about the documentation and comments as these won't change the results.

There could be a lot more to change but I know there will be some cleanup done once everything is in and we can check the results. And this is "legacy" code we bring in so we can't be too strict.

2024-06-18 00:04 UTC, ccarouge commented on src/offline/cable_parameters.F90
> +    !! vh_js !! comment out hide% condition
No double "!!" please as these are picked up by FORD in the documentation

```suggestion
    ! vh_js ! comment out hide% condition
```

2024-07-25 04:25 UTC, rkutteh commented on src/science/soilsnow/cbl_thermal.F90
> +    REAL, DIMENSION(mp)                      :: snowmlt !track snow melt
@ccarouge A couple of remarks regarding the requested change:

1. Is the dot in " REAL. " a typo or is it some new syntax I am not aware of ?
2. I realize that the requirement of JULES/UM is a must, but I think it is worth noting that this is not considered good coding practice, as attaching the dimension to the array name is the "old" way of declaring arrays and including the "DIMENSION" attribute in the declaration is the recommended "new" way. I think it is a good idea to double check that this is really what they want so we don't have a repetition of what happened earlier regarding breaking up the modules into smaller ones. 

I am happy to commit the suggestion once I hear back regarding the mysterious "dot"

2024-07-25 05:35 UTC, rkutteh commented on src/science/gw_hydro/cable_gw_hydro.F90
> +    !* This subrountine is called in subrountine surf_wetness_fact in cable_canopy.F90
```suggestion
  
```

2024-07-25 05:39 UTC, rkutteh commented on src/science/gw_hydro/cable_gw_hydro.F90
> +    !* This subrountine is called in subrountine surf_wetness_fact in cable_canopy.F90
Done

2024-07-25 05:43 UTC, rkutteh commented on src/offline/cable_parameters.F90
> +    where(veg%iveg .eq. 17) soil%isoilm = 9   ! MMY@13April it says where iveg = ice, isoilm = permanent ice
```suggestion
  
```

2024-07-25 05:45 UTC, rkutteh commented on src/offline/cable_parameters.F90
> +! line below inserted by rk4417 - phase2
```suggestion

```

2024-07-25 05:46 UTC, rkutteh commented on src/offline/cable_parameters.F90
> +    where(veg%iveg .eq. 17) soil%isoilm = 9   ! MMY@13April it says where iveg = ice, isoilm = permanent ice
Done

2024-07-25 08:37 UTC, rkutteh commented on src/science/gw_hydro/cable_gw_hydro.F90
> +   ! if max_ice_frac always set to frozen_limit and tgg_tmp is always CTFRZ
Yes, this subroutine is called only once from inside SUBROUTINE soil_snow_gw (inside cable_gw_hydro.F90). Not sure who put this comment in, but I suggest we leave it until the final clean-up phase of the GW project and worry about it then.

2024-08-01 23:21 UTC, ccarouge commented on src/science/soilsnow/cbl_thermal.F90
> +    REAL, DIMENSION(mp)                      :: snowmlt !track snow melt
The dot was indeed a typo. But on reflection, I would leave it as is.

2024-08-26 09:58 UTC, rkutteh commented
@ccarouge I have resolved the 4 conflicts. I am ready to merge when permitted, so I can then proceed with working on the next pull request.

2024-08-30 01:31 UTC, ccarouge approved these changes
All good to go. Sorry for the wait.

2024-08-30 01:36 UTC, rkutteh commented
Thanks Claire. We can cancel our chat today at 12:15 if you wish as I was waiting to merge the pull request to start on what remains, so there is not much to discuss today. However if you still wish to talk please let me know.



Thanks.
Ramzi
________________________________
From: Claire Carouge ***@***.***>
Sent: Friday, 30 August 2024 11:31 AM
To: CABLE-LSM/CABLE ***@***.***>
Cc: Ramzi Kutteh ***@***.***>; Mention ***@***.***>
Subject: Re: [CABLE-LSM/CABLE] Replace cable_gw_hydro.F90 with its new version (PR #231)


@ccarouge approved this pull request.

All good to go. Sorry for the wait.

—
Reply to this email directly, view it on GitHub<https://github.com/CABLE-LSM/CABLE/pull/231#pullrequestreview-2270758427>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AXR2B4HUD55XFSMGQI52SU3ZT7DP5AVCNFSM6AAAAABF3H5DZSVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDENZQG42TQNBSG4>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2024-09-01 10:41 UTC, merged