Review process for new contributions
CABLE-LSM/CABLE pull request #289
Opened 2024-05-10 05:23 UTC by ccarouge

# CABLE

Thank you for submitting a pull request to the CABLE Project.

## Description

Guidelines for the review of new contributions.

Fixes #186 

## Type of change

Please delete options that are not relevant.

- [X] New or updated documentation

## Checklist

- [ ] The new content is accessible and located in the appropriate section.
- [ ] I have checked that links are valid and point to the intended content.
- [ ] I have checked my code/text and corrected any misspellings

Please add a reviewer when ready for review.

2024-05-15 23:35 UTC, ccarouge commented
@bschroeter When writing this, I realised having a quick explanation of the PR interface in the CABLE documentation would be good. But I think it needs to come earlier in the contribution guidelines so I'm not including it with this work. 

The pages modified by this PR can be found [here](https://cable--289.org.readthedocs.build/en/289/developer_guide/contribution/review_guide/) and [here](https://cable--289.org.readthedocs.build/en/289/developer_guide/contribution/resources/how_to/) in the rendered documentation.

2024-05-15 23:46 UTC, bschroeter requested changes
Looks good - Just that one line by the looks of it.

2024-05-15 23:46 UTC, bschroeter commented on documentation/docs/developer_guide/contribution/review_guide.md
> +In most cases, asking for one reviewer is enough. The system allows asking for multiple reviewers, please use this feature will parsimony. It is often easier to ask for a single reviewer first and ad
```suggestion
In most cases, asking for one reviewer is enough. The system allows asking for multiple reviewers, please use this feature sparingly. It is often easier to ask for a single reviewer first and add another reviewer later as necessary.
```

Small typo, simplified language.

2024-05-21 01:19 UTC, bschroeter approved these changes

2024-05-21 01:20 UTC, bschroeter commented
Looks good, might want to check that markdown link check thing.

2024-07-03 06:45 UTC, ccarouge commented
The markdown checker is failing on files that have been removed from main but still exist in the outdated documentation in the PR branch. These will be removed from the documentation once merged with main.

2024-07-03 06:45 UTC, merged