Update value for checks%range
CABLE-LSM/CABLE pull request #345
Opened 2024-07-15 02:35 UTC by ccarouge

# CABLE

Thank you for submitting a pull request to the CABLE Project.

## Description

Fixes #344

## Type of change

Please delete options that are not relevant.

- [X] Bug fix

## Checklist

I have compiled the code and run the Tumbarumba test case with the updated namelist. The test case finished:
```
 Finished.    36.78621      seconds needed for year
 Finished.    36.78769      seconds needed for        70128  hours
```

Please add a reviewer when ready for review.

2024-07-15 02:36 UTC, ccarouge commented
@abhaasgoyal we forgot to update this namelist file with the changes to check the range.

2024-07-15 02:48 UTC, har917 reviewed
@ccarouge @abhaasgoyal   This change looks okay ... BUT ...

I'm not sure about previous change - we've switched from a TRUE/FALSE LOGICAL kind for `check%ranges` to an integer but there's still a few instances in the code of `IF(check%range)THEN`

I can see that working for `check%range=0,1` but not for `2` - at least with some compilers.

2024-07-15 05:10 UTC, har917 approved these changes
In testing #335 and #346 I tested with `check%ranges = 0, 1, 2`.  This would seem to be fine - at least for the compiler on gadi.

2024-07-15 05:31 UTC, ccarouge commented
@har917 The main branch does not currently compile with GNU compiler anyway for other reasons (the abort() function for example accepts a string argument with Intel but not GNU...). But I agree we should change the IF statements as we don't want to go further from compatibility with GNU than we currently are. It's just going to be tricky to see all of these without being able to compile. I'll add that change and update the issue.

2024-07-15 05:54 UTC, abhaasgoyal commented
For clarity, maybe we can have the check `check%ranges /= NO_CHECK` in the `IF` statement?

2024-07-16 01:13 UTC, abhaasgoyal approved these changes
LGTM

2024-07-16 01:15 UTC, abhaasgoyal requested changes
Edit: Apologies since already approved, but there was a small change which if done would be good. There are some `check%ranges=.TRUE.` in the documentation, which can also be changed (in `pft_params_nml.md`, and `meteorological_forcings.md`.

2024-07-16 02:46 UTC, abhaasgoyal approved these changes
LGTM

2024-07-16 05:20 UTC, merged