Update cbl_init_radiation.F90
CABLE-LSM/CABLE pull request #41
Opened 2022-11-07 00:06 UTC by heidinett

"HN modification 07.11.22"

# CABLE

Thank you for submitting a pull request to the CABLE Project.

## Description

Please include a brief summary of the change and list the issues that are fixed.
Please also include relevant motivation and context.

You can link issues by using a supported keyword in the pull request's description or in a commit message:

Fixes #(issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix
- [ ] New or updated documentation

## Checklist

- [ ] The new content is accessible and located in the appropriate section.
- [ ] I have checked that links are valid and point to the intended content.
- [ ] I have checked my code/text and corrected any misspellings

Please add a reviewer when ready for review.

2022-11-07 00:43 UTC, bibivking requested changes
:)

2022-11-07 00:43 UTC, bibivking commented on src/science/radiation/cbl_init_radiation.F90
> +!! I have no idea if this change will be noticed. HN mod 07.11.22
```suggestion
!! I have no idea if this change will be noticed. HN mod 07.11.22 - hahahahahha
```

2022-11-07 01:06 UTC, bibivking approved these changes

2022-11-10 01:28 UTC, ccarouge commented
This was a test only. Close without merging.

2022-11-10 01:28 UTC, closed without merging